[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
loss_harvester = "2MsxpVjLVPfGmVnh4RDeahbRv65uqvMLJrgTdHxyE8CN"

[programs.devnet]
loss_harvester = "2MsxpVjLVPfGmVnh4RDeahbRv65uqvMLJrgTdHxyE8CN"

[programs.mainnet]
loss_harvester = "2MsxpVjLVPfGmVnh4RDeahbRv65uqvMLJrgTdHxyE8CN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
