[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
loss_harvester = "3HbRiF7A9vBNwLgkFyafidxPBrTH4W7PUwz8iHPkntsH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
